/**
 * VLBMX Database Schema
 *
 * NOTE: User/auth tables will be generated by Better Auth in Phase 2.
 * Do NOT manually define user tables here — they will conflict.
 * This file is the single source of truth for all application-specific tables.
 *
 * @see https://orm.drizzle.team/docs/sql-schema-declaration
 */

// Placeholder export to satisfy TypeScript module resolution.
// Better Auth tables (users, sessions, accounts, verifications) will be
// added here in Phase 2 via the Better Auth Drizzle adapter.
// Application-specific tables (games, streams, etc.) will follow.
export {};
